// <auto-generated />
using System;
using Avonale_Prova.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Avonale_Prova.Migrations
{
    [DbContext(typeof(ProdutoDbContext))]
    partial class ProdutoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Avonale_Prova.Models.Cartao", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("CartaoCredito")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bandeira")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("cvv")
                        .HasColumnType("int");

                    b.Property<string>("data_expiracao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("titular")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Cartoes");
                });

            modelBuilder.Entity("Avonale_Prova.Models.Comprar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("cartaoid")
                        .HasColumnType("int");

                    b.Property<int>("produto_id")
                        .HasColumnType("int");

                    b.Property<int>("qtde_comprada")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("cartaoid");

                    b.ToTable("Compras");
                });

            modelBuilder.Entity("Avonale_Prova.Models.Pagamento", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<int>("cartaoid")
                        .HasColumnType("int");

                    b.Property<string>("estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("valor")
                        .HasColumnType("real");

                    b.HasKey("id");

                    b.HasIndex("cartaoid");

                    b.ToTable("Pagamentos");
                });

            modelBuilder.Entity("Avonale_Prova.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("Ultima_venda")
                        .HasColumnType("datetime2");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("qtde_estoque")
                        .HasColumnType("int");

                    b.Property<float?>("valor_ultima_venda")
                        .HasColumnType("real");

                    b.Property<float>("valor_unitario")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("Avonale_Prova.Models.Comprar", b =>
                {
                    b.HasOne("Avonale_Prova.Models.Cartao", "cartao")
                        .WithMany()
                        .HasForeignKey("cartaoid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("cartao");
                });

            modelBuilder.Entity("Avonale_Prova.Models.Pagamento", b =>
                {
                    b.HasOne("Avonale_Prova.Models.Cartao", "cartao")
                        .WithMany()
                        .HasForeignKey("cartaoid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("cartao");
                });
#pragma warning restore 612, 618
        }
    }
}
